// Generated by belt data studio. Do not edit manually.

use std::collections::HashMap;

use data_studio_core::RowId;

use crate::table_accessors::GeneratedDatabase;

#[derive(Debug, Clone, Default)]
pub struct GeneratedRelationCache {
    pub unit_def_visual: HashMap<RowId, RowId>,
    pub unit_def_skills: HashMap<RowId, Vec<RowId>>,
    pub unit_def_behavior_rules: HashMap<RowId, Vec<RowId>>,
    pub unit_def_base_stats: HashMap<RowId, Vec<RowId>>,
    pub unit_group_members: HashMap<RowId, Vec<RowId>>,
    pub wave_def_enemy_groups: HashMap<RowId, Vec<RowId>>,
    pub map_def_party: HashMap<RowId, RowId>,
    pub map_def_waves: HashMap<RowId, Vec<RowId>>,
    pub map_def_drop_table: HashMap<RowId, RowId>,
    pub unit_group_member_unit: HashMap<RowId, RowId>,
    pub sprite_animation_texture: HashMap<RowId, RowId>,
    pub sprite_animation_frames: HashMap<RowId, Vec<RowId>>,
    pub visual_state_machine_default_state: HashMap<RowId, RowId>,
    pub visual_state_machine_states: HashMap<RowId, Vec<RowId>>,
    pub visual_state_animation: HashMap<RowId, RowId>,
    pub unit_visual_state_machine: HashMap<RowId, RowId>,
    pub sprite_frame_texture: HashMap<RowId, RowId>,
    pub drop_table_entries: HashMap<RowId, Vec<RowId>>,
    pub drop_entry_item: HashMap<RowId, RowId>,
    pub storage_tab_config_upgrade_currency: HashMap<RowId, RowId>,
    pub skill_def_cast_pattern: HashMap<RowId, RowId>,
    pub skill_def_steps: HashMap<RowId, Vec<RowId>>,
    pub skill_def_costs: HashMap<RowId, Vec<RowId>>,
    pub skill_step_pattern: HashMap<RowId, RowId>,
    pub skill_step_effects: HashMap<RowId, Vec<RowId>>,
    pub skill_effect_trigger_skill: HashMap<RowId, RowId>,
    pub skill_effect_impact_pattern: HashMap<RowId, RowId>,
    pub skill_effect_stat: HashMap<RowId, RowId>,
    pub cell_pattern_cells: HashMap<RowId, Vec<RowId>>,
    pub behavior_rule_skill: HashMap<RowId, RowId>,
    pub behavior_rule_conditions: HashMap<RowId, Vec<RowId>>,
    pub unit_base_stat_stat: HashMap<RowId, RowId>,
    pub condition_def_stat: HashMap<RowId, RowId>,
    pub condition_def_other_stat: HashMap<RowId, RowId>,
    pub skill_stat_cost_stat: HashMap<RowId, RowId>,
    pub alchemy_recipe_output_item: HashMap<RowId, RowId>,
    pub alchemy_recipe_ingredients: HashMap<RowId, Vec<RowId>>,
    pub recipe_ingredient_item: HashMap<RowId, RowId>,
    pub forge_recipe_recipe_item: HashMap<RowId, RowId>,
    pub forge_recipe_output_item: HashMap<RowId, RowId>,
    pub forge_recipe_ingredients: HashMap<RowId, Vec<RowId>>,
    pub forge_ingredient_item: HashMap<RowId, RowId>,
    pub refinement_recipe_input_equipment: HashMap<RowId, RowId>,
    pub refinement_recipe_material_item: HashMap<RowId, RowId>,
    pub refinement_recipe_output_item: HashMap<RowId, RowId>,
    pub refinement_recipe_special_options: HashMap<RowId, Vec<RowId>>,
    pub refinement_recipe_effects: HashMap<RowId, Vec<RowId>>,
    pub special_option_def_stat_deltas: HashMap<RowId, Vec<RowId>>,
    pub special_option_def_granted_skill: HashMap<RowId, RowId>,
    pub special_option_def_skill_mutations: HashMap<RowId, Vec<RowId>>,
    pub special_option_stat_delta_stat: HashMap<RowId, RowId>,
    pub unit_special_option_loadout_unit: HashMap<RowId, RowId>,
    pub unit_special_option_loadout_special_options: HashMap<RowId, Vec<RowId>>,
    pub special_trigger_def_stack_stat: HashMap<RowId, RowId>,
    pub special_trigger_def_conditions: HashMap<RowId, Vec<RowId>>,
    pub special_trigger_def_effects: HashMap<RowId, Vec<RowId>>,
    pub special_trigger_condition_stat: HashMap<RowId, RowId>,
    pub special_trigger_effect_stat: HashMap<RowId, RowId>,
    pub special_trigger_effect_trigger_skill: HashMap<RowId, RowId>,
    pub special_option_skill_mutation_target_skill: HashMap<RowId, RowId>,
    pub refinement_effect_special_options: HashMap<RowId, Vec<RowId>>,
    pub refinement_effect_option_pool: HashMap<RowId, Vec<RowId>>,
}

impl GeneratedRelationCache {
    pub fn build(db: &GeneratedDatabase) -> Result<Self, String> {
        let mut cache = Self::default();
        for row in &db.unit_def.rows {
            if db.unit_visual.get_by_id(row.visual).is_none() {
                return Err(format!(
                    "missing relation target for unit_def.visual from {:?} to {:?}",
                    row.id, row.visual
                ));
            }
            cache.unit_def_visual.insert(row.id, row.visual);
        }
        for row in &db.unit_def.rows {
            for target_id in &row.skills {
                if db.skill_def.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for unit_def.skills from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.unit_def_skills.insert(row.id, row.skills.clone());
        }
        for row in &db.unit_def.rows {
            for target_id in &row.behavior_rules {
                if db.behavior_rule.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for unit_def.behavior_rules from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .unit_def_behavior_rules
                .insert(row.id, row.behavior_rules.clone());
        }
        for row in &db.unit_def.rows {
            for target_id in &row.base_stats {
                if db.unit_base_stat.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for unit_def.base_stats from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .unit_def_base_stats
                .insert(row.id, row.base_stats.clone());
        }
        for row in &db.unit_group.rows {
            for target_id in &row.members {
                if db.unit_group_member.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for unit_group.members from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.unit_group_members.insert(row.id, row.members.clone());
        }
        for row in &db.wave_def.rows {
            for target_id in &row.enemy_groups {
                if db.unit_group.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for wave_def.enemy_groups from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .wave_def_enemy_groups
                .insert(row.id, row.enemy_groups.clone());
        }
        for row in &db.map_def.rows {
            if db.unit_group.get_by_id(row.party).is_none() {
                return Err(format!(
                    "missing relation target for map_def.party from {:?} to {:?}",
                    row.id, row.party
                ));
            }
            cache.map_def_party.insert(row.id, row.party);
        }
        for row in &db.map_def.rows {
            for target_id in &row.waves {
                if db.wave_def.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for map_def.waves from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.map_def_waves.insert(row.id, row.waves.clone());
        }
        for row in &db.map_def.rows {
            if db.drop_table.get_by_id(row.drop_table).is_none() {
                return Err(format!(
                    "missing relation target for map_def.drop_table from {:?} to {:?}",
                    row.id, row.drop_table
                ));
            }
            cache.map_def_drop_table.insert(row.id, row.drop_table);
        }
        for row in &db.unit_group_member.rows {
            if db.unit_def.get_by_id(row.unit).is_none() {
                return Err(format!(
                    "missing relation target for unit_group_member.unit from {:?} to {:?}",
                    row.id, row.unit
                ));
            }
            cache.unit_group_member_unit.insert(row.id, row.unit);
        }
        for row in &db.sprite_animation.rows {
            if db.texture_asset.get_by_id(row.texture).is_none() {
                return Err(format!(
                    "missing relation target for sprite_animation.texture from {:?} to {:?}",
                    row.id, row.texture
                ));
            }
            cache.sprite_animation_texture.insert(row.id, row.texture);
        }
        for row in &db.sprite_animation.rows {
            for target_id in &row.frames {
                if db.sprite_frame.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for sprite_animation.frames from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .sprite_animation_frames
                .insert(row.id, row.frames.clone());
        }
        for row in &db.visual_state_machine.rows {
            if db.visual_state.get_by_id(row.default_state).is_none() {
                return Err(format!("missing relation target for visual_state_machine.default_state from {:?} to {:?}", row.id, row.default_state));
            }
            cache
                .visual_state_machine_default_state
                .insert(row.id, row.default_state);
        }
        for row in &db.visual_state_machine.rows {
            for target_id in &row.states {
                if db.visual_state.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for visual_state_machine.states from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .visual_state_machine_states
                .insert(row.id, row.states.clone());
        }
        for row in &db.visual_state.rows {
            if db.sprite_animation.get_by_id(row.animation).is_none() {
                return Err(format!(
                    "missing relation target for visual_state.animation from {:?} to {:?}",
                    row.id, row.animation
                ));
            }
            cache.visual_state_animation.insert(row.id, row.animation);
        }
        for row in &db.unit_visual.rows {
            if db
                .visual_state_machine
                .get_by_id(row.state_machine)
                .is_none()
            {
                return Err(format!(
                    "missing relation target for unit_visual.state_machine from {:?} to {:?}",
                    row.id, row.state_machine
                ));
            }
            cache
                .unit_visual_state_machine
                .insert(row.id, row.state_machine);
        }
        for row in &db.sprite_frame.rows {
            if db.texture_asset.get_by_id(row.texture).is_none() {
                return Err(format!(
                    "missing relation target for sprite_frame.texture from {:?} to {:?}",
                    row.id, row.texture
                ));
            }
            cache.sprite_frame_texture.insert(row.id, row.texture);
        }
        for row in &db.drop_table.rows {
            for target_id in &row.entries {
                if db.drop_entry.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for drop_table.entries from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.drop_table_entries.insert(row.id, row.entries.clone());
        }
        for row in &db.drop_entry.rows {
            if db.item_def.get_by_id(row.item).is_none() {
                return Err(format!(
                    "missing relation target for drop_entry.item from {:?} to {:?}",
                    row.id, row.item
                ));
            }
            cache.drop_entry_item.insert(row.id, row.item);
        }
        for row in &db.storage_tab_config.rows {
            if db.item_def.get_by_id(row.upgrade_currency).is_none() {
                return Err(format!("missing relation target for storage_tab_config.upgrade_currency from {:?} to {:?}", row.id, row.upgrade_currency));
            }
            cache
                .storage_tab_config_upgrade_currency
                .insert(row.id, row.upgrade_currency);
        }
        for row in &db.skill_def.rows {
            if db.cell_pattern.get_by_id(row.cast_pattern).is_none() {
                return Err(format!(
                    "missing relation target for skill_def.cast_pattern from {:?} to {:?}",
                    row.id, row.cast_pattern
                ));
            }
            cache
                .skill_def_cast_pattern
                .insert(row.id, row.cast_pattern);
        }
        for row in &db.skill_def.rows {
            for target_id in &row.steps {
                if db.skill_step.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for skill_def.steps from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.skill_def_steps.insert(row.id, row.steps.clone());
        }
        for row in &db.skill_def.rows {
            for target_id in &row.costs {
                if db.skill_stat_cost.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for skill_def.costs from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.skill_def_costs.insert(row.id, row.costs.clone());
        }
        for row in &db.skill_step.rows {
            if db.cell_pattern.get_by_id(row.pattern).is_none() {
                return Err(format!(
                    "missing relation target for skill_step.pattern from {:?} to {:?}",
                    row.id, row.pattern
                ));
            }
            cache.skill_step_pattern.insert(row.id, row.pattern);
        }
        for row in &db.skill_step.rows {
            for target_id in &row.effects {
                if db.skill_effect.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for skill_step.effects from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.skill_step_effects.insert(row.id, row.effects.clone());
        }
        for row in &db.skill_effect.rows {
            if db.skill_def.get_by_id(row.trigger_skill).is_none() {
                return Err(format!(
                    "missing relation target for skill_effect.trigger_skill from {:?} to {:?}",
                    row.id, row.trigger_skill
                ));
            }
            cache
                .skill_effect_trigger_skill
                .insert(row.id, row.trigger_skill);
        }
        for row in &db.skill_effect.rows {
            if db.cell_pattern.get_by_id(row.impact_pattern).is_none() {
                return Err(format!(
                    "missing relation target for skill_effect.impact_pattern from {:?} to {:?}",
                    row.id, row.impact_pattern
                ));
            }
            cache
                .skill_effect_impact_pattern
                .insert(row.id, row.impact_pattern);
        }
        for row in &db.skill_effect.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for skill_effect.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache.skill_effect_stat.insert(row.id, row.stat);
        }
        for row in &db.cell_pattern.rows {
            for target_id in &row.cells {
                if db.cell_offset.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for cell_pattern.cells from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache.cell_pattern_cells.insert(row.id, row.cells.clone());
        }
        for row in &db.behavior_rule.rows {
            if db.skill_def.get_by_id(row.skill).is_none() {
                return Err(format!(
                    "missing relation target for behavior_rule.skill from {:?} to {:?}",
                    row.id, row.skill
                ));
            }
            cache.behavior_rule_skill.insert(row.id, row.skill);
        }
        for row in &db.behavior_rule.rows {
            for target_id in &row.conditions {
                if db.condition_def.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for behavior_rule.conditions from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .behavior_rule_conditions
                .insert(row.id, row.conditions.clone());
        }
        for row in &db.unit_base_stat.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for unit_base_stat.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache.unit_base_stat_stat.insert(row.id, row.stat);
        }
        for row in &db.condition_def.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for condition_def.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache.condition_def_stat.insert(row.id, row.stat);
        }
        for row in &db.condition_def.rows {
            if db.stat_def.get_by_id(row.other_stat).is_none() {
                return Err(format!(
                    "missing relation target for condition_def.other_stat from {:?} to {:?}",
                    row.id, row.other_stat
                ));
            }
            cache
                .condition_def_other_stat
                .insert(row.id, row.other_stat);
        }
        for row in &db.skill_stat_cost.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for skill_stat_cost.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache.skill_stat_cost_stat.insert(row.id, row.stat);
        }
        for row in &db.alchemy_recipe.rows {
            if db.item_def.get_by_id(row.output_item).is_none() {
                return Err(format!(
                    "missing relation target for alchemy_recipe.output_item from {:?} to {:?}",
                    row.id, row.output_item
                ));
            }
            cache
                .alchemy_recipe_output_item
                .insert(row.id, row.output_item);
        }
        for row in &db.alchemy_recipe.rows {
            for target_id in &row.ingredients {
                if db.recipe_ingredient.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for alchemy_recipe.ingredients from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .alchemy_recipe_ingredients
                .insert(row.id, row.ingredients.clone());
        }
        for row in &db.recipe_ingredient.rows {
            if db.item_def.get_by_id(row.item).is_none() {
                return Err(format!(
                    "missing relation target for recipe_ingredient.item from {:?} to {:?}",
                    row.id, row.item
                ));
            }
            cache.recipe_ingredient_item.insert(row.id, row.item);
        }
        for row in &db.forge_recipe.rows {
            if db.item_def.get_by_id(row.recipe_item).is_none() {
                return Err(format!(
                    "missing relation target for forge_recipe.recipe_item from {:?} to {:?}",
                    row.id, row.recipe_item
                ));
            }
            cache
                .forge_recipe_recipe_item
                .insert(row.id, row.recipe_item);
        }
        for row in &db.forge_recipe.rows {
            if db.item_def.get_by_id(row.output_item).is_none() {
                return Err(format!(
                    "missing relation target for forge_recipe.output_item from {:?} to {:?}",
                    row.id, row.output_item
                ));
            }
            cache
                .forge_recipe_output_item
                .insert(row.id, row.output_item);
        }
        for row in &db.forge_recipe.rows {
            for target_id in &row.ingredients {
                if db.forge_ingredient.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for forge_recipe.ingredients from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .forge_recipe_ingredients
                .insert(row.id, row.ingredients.clone());
        }
        for row in &db.forge_ingredient.rows {
            if db.item_def.get_by_id(row.item).is_none() {
                return Err(format!(
                    "missing relation target for forge_ingredient.item from {:?} to {:?}",
                    row.id, row.item
                ));
            }
            cache.forge_ingredient_item.insert(row.id, row.item);
        }
        for row in &db.refinement_recipe.rows {
            if db.item_def.get_by_id(row.input_equipment).is_none() {
                return Err(format!("missing relation target for refinement_recipe.input_equipment from {:?} to {:?}", row.id, row.input_equipment));
            }
            cache
                .refinement_recipe_input_equipment
                .insert(row.id, row.input_equipment);
        }
        for row in &db.refinement_recipe.rows {
            if db.item_def.get_by_id(row.material_item).is_none() {
                return Err(format!(
                    "missing relation target for refinement_recipe.material_item from {:?} to {:?}",
                    row.id, row.material_item
                ));
            }
            cache
                .refinement_recipe_material_item
                .insert(row.id, row.material_item);
        }
        for row in &db.refinement_recipe.rows {
            if db.item_def.get_by_id(row.output_item).is_none() {
                return Err(format!(
                    "missing relation target for refinement_recipe.output_item from {:?} to {:?}",
                    row.id, row.output_item
                ));
            }
            cache
                .refinement_recipe_output_item
                .insert(row.id, row.output_item);
        }
        for row in &db.refinement_recipe.rows {
            for target_id in &row.special_options {
                if db.special_option_def.get_by_id(*target_id).is_none() {
                    return Err(format!("missing relation target for refinement_recipe.special_options from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .refinement_recipe_special_options
                .insert(row.id, row.special_options.clone());
        }
        for row in &db.refinement_recipe.rows {
            for target_id in &row.effects {
                if db.refinement_effect.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for refinement_recipe.effects from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .refinement_recipe_effects
                .insert(row.id, row.effects.clone());
        }
        for row in &db.special_option_def.rows {
            for target_id in &row.stat_deltas {
                if db.special_option_stat_delta.get_by_id(*target_id).is_none() {
                    return Err(format!("missing relation target for special_option_def.stat_deltas from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .special_option_def_stat_deltas
                .insert(row.id, row.stat_deltas.clone());
        }
        for row in &db.special_option_def.rows {
            if db.skill_def.get_by_id(row.granted_skill).is_none() {
                return Err(format!("missing relation target for special_option_def.granted_skill from {:?} to {:?}", row.id, row.granted_skill));
            }
            cache
                .special_option_def_granted_skill
                .insert(row.id, row.granted_skill);
        }
        for row in &db.special_option_def.rows {
            for target_id in &row.skill_mutations {
                if db
                    .special_option_skill_mutation
                    .get_by_id(*target_id)
                    .is_none()
                {
                    return Err(format!("missing relation target for special_option_def.skill_mutations from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .special_option_def_skill_mutations
                .insert(row.id, row.skill_mutations.clone());
        }
        for row in &db.special_option_stat_delta.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for special_option_stat_delta.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache
                .special_option_stat_delta_stat
                .insert(row.id, row.stat);
        }
        for row in &db.unit_special_option_loadout.rows {
            if db.unit_def.get_by_id(row.unit).is_none() {
                return Err(format!("missing relation target for unit_special_option_loadout.unit from {:?} to {:?}", row.id, row.unit));
            }
            cache
                .unit_special_option_loadout_unit
                .insert(row.id, row.unit);
        }
        for row in &db.unit_special_option_loadout.rows {
            for target_id in &row.special_options {
                if db.special_option_def.get_by_id(*target_id).is_none() {
                    return Err(format!("missing relation target for unit_special_option_loadout.special_options from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .unit_special_option_loadout_special_options
                .insert(row.id, row.special_options.clone());
        }
        for row in &db.special_trigger_def.rows {
            if db.stat_def.get_by_id(row.stack_stat).is_none() {
                return Err(format!(
                    "missing relation target for special_trigger_def.stack_stat from {:?} to {:?}",
                    row.id, row.stack_stat
                ));
            }
            cache
                .special_trigger_def_stack_stat
                .insert(row.id, row.stack_stat);
        }
        for row in &db.special_trigger_def.rows {
            for target_id in &row.conditions {
                if db.special_trigger_condition.get_by_id(*target_id).is_none() {
                    return Err(format!("missing relation target for special_trigger_def.conditions from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .special_trigger_def_conditions
                .insert(row.id, row.conditions.clone());
        }
        for row in &db.special_trigger_def.rows {
            for target_id in &row.effects {
                if db.special_trigger_effect.get_by_id(*target_id).is_none() {
                    return Err(format!(
                        "missing relation target for special_trigger_def.effects from {:?} to {:?}",
                        row.id, target_id
                    ));
                }
            }
            cache
                .special_trigger_def_effects
                .insert(row.id, row.effects.clone());
        }
        for row in &db.special_trigger_condition.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for special_trigger_condition.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache
                .special_trigger_condition_stat
                .insert(row.id, row.stat);
        }
        for row in &db.special_trigger_effect.rows {
            if db.stat_def.get_by_id(row.stat).is_none() {
                return Err(format!(
                    "missing relation target for special_trigger_effect.stat from {:?} to {:?}",
                    row.id, row.stat
                ));
            }
            cache.special_trigger_effect_stat.insert(row.id, row.stat);
        }
        for row in &db.special_trigger_effect.rows {
            if db.skill_def.get_by_id(row.trigger_skill).is_none() {
                return Err(format!("missing relation target for special_trigger_effect.trigger_skill from {:?} to {:?}", row.id, row.trigger_skill));
            }
            cache
                .special_trigger_effect_trigger_skill
                .insert(row.id, row.trigger_skill);
        }
        for row in &db.special_option_skill_mutation.rows {
            if db.skill_def.get_by_id(row.target_skill).is_none() {
                return Err(format!("missing relation target for special_option_skill_mutation.target_skill from {:?} to {:?}", row.id, row.target_skill));
            }
            cache
                .special_option_skill_mutation_target_skill
                .insert(row.id, row.target_skill);
        }
        for row in &db.refinement_effect.rows {
            for target_id in &row.special_options {
                if db.special_option_def.get_by_id(*target_id).is_none() {
                    return Err(format!("missing relation target for refinement_effect.special_options from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .refinement_effect_special_options
                .insert(row.id, row.special_options.clone());
        }
        for row in &db.refinement_effect.rows {
            for target_id in &row.option_pool {
                if db
                    .refinement_option_pool_entry
                    .get_by_id(*target_id)
                    .is_none()
                {
                    return Err(format!("missing relation target for refinement_effect.option_pool from {:?} to {:?}", row.id, target_id));
                }
            }
            cache
                .refinement_effect_option_pool
                .insert(row.id, row.option_pool.clone());
        }
        Ok(cache)
    }

    pub fn get_unit_def_visual(&self, source: RowId) -> Option<RowId> {
        self.unit_def_visual.get(&source).copied()
    }

    pub fn get_unit_def_skills(&self, source: RowId) -> Option<&[RowId]> {
        self.unit_def_skills.get(&source).map(Vec::as_slice)
    }

    pub fn get_unit_def_behavior_rules(&self, source: RowId) -> Option<&[RowId]> {
        self.unit_def_behavior_rules.get(&source).map(Vec::as_slice)
    }

    pub fn get_unit_def_base_stats(&self, source: RowId) -> Option<&[RowId]> {
        self.unit_def_base_stats.get(&source).map(Vec::as_slice)
    }

    pub fn get_unit_group_members(&self, source: RowId) -> Option<&[RowId]> {
        self.unit_group_members.get(&source).map(Vec::as_slice)
    }

    pub fn get_wave_def_enemy_groups(&self, source: RowId) -> Option<&[RowId]> {
        self.wave_def_enemy_groups.get(&source).map(Vec::as_slice)
    }

    pub fn get_map_def_party(&self, source: RowId) -> Option<RowId> {
        self.map_def_party.get(&source).copied()
    }

    pub fn get_map_def_waves(&self, source: RowId) -> Option<&[RowId]> {
        self.map_def_waves.get(&source).map(Vec::as_slice)
    }

    pub fn get_map_def_drop_table(&self, source: RowId) -> Option<RowId> {
        self.map_def_drop_table.get(&source).copied()
    }

    pub fn get_unit_group_member_unit(&self, source: RowId) -> Option<RowId> {
        self.unit_group_member_unit.get(&source).copied()
    }

    pub fn get_sprite_animation_texture(&self, source: RowId) -> Option<RowId> {
        self.sprite_animation_texture.get(&source).copied()
    }

    pub fn get_sprite_animation_frames(&self, source: RowId) -> Option<&[RowId]> {
        self.sprite_animation_frames.get(&source).map(Vec::as_slice)
    }

    pub fn get_visual_state_machine_default_state(&self, source: RowId) -> Option<RowId> {
        self.visual_state_machine_default_state
            .get(&source)
            .copied()
    }

    pub fn get_visual_state_machine_states(&self, source: RowId) -> Option<&[RowId]> {
        self.visual_state_machine_states
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_visual_state_animation(&self, source: RowId) -> Option<RowId> {
        self.visual_state_animation.get(&source).copied()
    }

    pub fn get_unit_visual_state_machine(&self, source: RowId) -> Option<RowId> {
        self.unit_visual_state_machine.get(&source).copied()
    }

    pub fn get_sprite_frame_texture(&self, source: RowId) -> Option<RowId> {
        self.sprite_frame_texture.get(&source).copied()
    }

    pub fn get_drop_table_entries(&self, source: RowId) -> Option<&[RowId]> {
        self.drop_table_entries.get(&source).map(Vec::as_slice)
    }

    pub fn get_drop_entry_item(&self, source: RowId) -> Option<RowId> {
        self.drop_entry_item.get(&source).copied()
    }

    pub fn get_storage_tab_config_upgrade_currency(&self, source: RowId) -> Option<RowId> {
        self.storage_tab_config_upgrade_currency
            .get(&source)
            .copied()
    }

    pub fn get_skill_def_cast_pattern(&self, source: RowId) -> Option<RowId> {
        self.skill_def_cast_pattern.get(&source).copied()
    }

    pub fn get_skill_def_steps(&self, source: RowId) -> Option<&[RowId]> {
        self.skill_def_steps.get(&source).map(Vec::as_slice)
    }

    pub fn get_skill_def_costs(&self, source: RowId) -> Option<&[RowId]> {
        self.skill_def_costs.get(&source).map(Vec::as_slice)
    }

    pub fn get_skill_step_pattern(&self, source: RowId) -> Option<RowId> {
        self.skill_step_pattern.get(&source).copied()
    }

    pub fn get_skill_step_effects(&self, source: RowId) -> Option<&[RowId]> {
        self.skill_step_effects.get(&source).map(Vec::as_slice)
    }

    pub fn get_skill_effect_trigger_skill(&self, source: RowId) -> Option<RowId> {
        self.skill_effect_trigger_skill.get(&source).copied()
    }

    pub fn get_skill_effect_impact_pattern(&self, source: RowId) -> Option<RowId> {
        self.skill_effect_impact_pattern.get(&source).copied()
    }

    pub fn get_skill_effect_stat(&self, source: RowId) -> Option<RowId> {
        self.skill_effect_stat.get(&source).copied()
    }

    pub fn get_cell_pattern_cells(&self, source: RowId) -> Option<&[RowId]> {
        self.cell_pattern_cells.get(&source).map(Vec::as_slice)
    }

    pub fn get_behavior_rule_skill(&self, source: RowId) -> Option<RowId> {
        self.behavior_rule_skill.get(&source).copied()
    }

    pub fn get_behavior_rule_conditions(&self, source: RowId) -> Option<&[RowId]> {
        self.behavior_rule_conditions
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_unit_base_stat_stat(&self, source: RowId) -> Option<RowId> {
        self.unit_base_stat_stat.get(&source).copied()
    }

    pub fn get_condition_def_stat(&self, source: RowId) -> Option<RowId> {
        self.condition_def_stat.get(&source).copied()
    }

    pub fn get_condition_def_other_stat(&self, source: RowId) -> Option<RowId> {
        self.condition_def_other_stat.get(&source).copied()
    }

    pub fn get_skill_stat_cost_stat(&self, source: RowId) -> Option<RowId> {
        self.skill_stat_cost_stat.get(&source).copied()
    }

    pub fn get_alchemy_recipe_output_item(&self, source: RowId) -> Option<RowId> {
        self.alchemy_recipe_output_item.get(&source).copied()
    }

    pub fn get_alchemy_recipe_ingredients(&self, source: RowId) -> Option<&[RowId]> {
        self.alchemy_recipe_ingredients
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_recipe_ingredient_item(&self, source: RowId) -> Option<RowId> {
        self.recipe_ingredient_item.get(&source).copied()
    }

    pub fn get_forge_recipe_recipe_item(&self, source: RowId) -> Option<RowId> {
        self.forge_recipe_recipe_item.get(&source).copied()
    }

    pub fn get_forge_recipe_output_item(&self, source: RowId) -> Option<RowId> {
        self.forge_recipe_output_item.get(&source).copied()
    }

    pub fn get_forge_recipe_ingredients(&self, source: RowId) -> Option<&[RowId]> {
        self.forge_recipe_ingredients
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_forge_ingredient_item(&self, source: RowId) -> Option<RowId> {
        self.forge_ingredient_item.get(&source).copied()
    }

    pub fn get_refinement_recipe_input_equipment(&self, source: RowId) -> Option<RowId> {
        self.refinement_recipe_input_equipment.get(&source).copied()
    }

    pub fn get_refinement_recipe_material_item(&self, source: RowId) -> Option<RowId> {
        self.refinement_recipe_material_item.get(&source).copied()
    }

    pub fn get_refinement_recipe_output_item(&self, source: RowId) -> Option<RowId> {
        self.refinement_recipe_output_item.get(&source).copied()
    }

    pub fn get_refinement_recipe_special_options(&self, source: RowId) -> Option<&[RowId]> {
        self.refinement_recipe_special_options
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_refinement_recipe_effects(&self, source: RowId) -> Option<&[RowId]> {
        self.refinement_recipe_effects
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_special_option_def_stat_deltas(&self, source: RowId) -> Option<&[RowId]> {
        self.special_option_def_stat_deltas
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_special_option_def_granted_skill(&self, source: RowId) -> Option<RowId> {
        self.special_option_def_granted_skill.get(&source).copied()
    }

    pub fn get_special_option_def_skill_mutations(&self, source: RowId) -> Option<&[RowId]> {
        self.special_option_def_skill_mutations
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_special_option_stat_delta_stat(&self, source: RowId) -> Option<RowId> {
        self.special_option_stat_delta_stat.get(&source).copied()
    }

    pub fn get_unit_special_option_loadout_unit(&self, source: RowId) -> Option<RowId> {
        self.unit_special_option_loadout_unit.get(&source).copied()
    }

    pub fn get_unit_special_option_loadout_special_options(
        &self,
        source: RowId,
    ) -> Option<&[RowId]> {
        self.unit_special_option_loadout_special_options
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_special_trigger_def_stack_stat(&self, source: RowId) -> Option<RowId> {
        self.special_trigger_def_stack_stat.get(&source).copied()
    }

    pub fn get_special_trigger_def_conditions(&self, source: RowId) -> Option<&[RowId]> {
        self.special_trigger_def_conditions
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_special_trigger_def_effects(&self, source: RowId) -> Option<&[RowId]> {
        self.special_trigger_def_effects
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_special_trigger_condition_stat(&self, source: RowId) -> Option<RowId> {
        self.special_trigger_condition_stat.get(&source).copied()
    }

    pub fn get_special_trigger_effect_stat(&self, source: RowId) -> Option<RowId> {
        self.special_trigger_effect_stat.get(&source).copied()
    }

    pub fn get_special_trigger_effect_trigger_skill(&self, source: RowId) -> Option<RowId> {
        self.special_trigger_effect_trigger_skill
            .get(&source)
            .copied()
    }

    pub fn get_special_option_skill_mutation_target_skill(&self, source: RowId) -> Option<RowId> {
        self.special_option_skill_mutation_target_skill
            .get(&source)
            .copied()
    }

    pub fn get_refinement_effect_special_options(&self, source: RowId) -> Option<&[RowId]> {
        self.refinement_effect_special_options
            .get(&source)
            .map(Vec::as_slice)
    }

    pub fn get_refinement_effect_option_pool(&self, source: RowId) -> Option<&[RowId]> {
        self.refinement_effect_option_pool
            .get(&source)
            .map(Vec::as_slice)
    }
}
