// Generated by belt data studio. Do not edit manually.

use data_studio_core::RowId;

#[derive(Debug, Clone)]
pub struct UnitDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub max_hp: i32,
    pub attack: i32,
    pub attack_range: f32,
    pub attack_interval: f32,
    pub move_speed: f32,
    pub visual: RowId,
}

#[derive(Debug, Clone)]
pub struct UnitGroup {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub members: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct WaveDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub enemy_groups: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct MapDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub party: RowId,
    pub waves: Vec<RowId>,
    pub left_scroll_speed: f32,
    pub wave_spawn_x: f32,
}

#[derive(Debug, Clone)]
pub struct UnitGroupMember {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub unit: RowId,
    pub x: f32,
    pub lane: f32,
}

#[derive(Debug, Clone)]
pub struct TextureAsset {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub path: String,
    pub width: i32,
    pub height: i32,
}

#[derive(Debug, Clone)]
pub struct SpriteAnimation {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub texture: RowId,
    pub frame_count: i32,
    pub fps: f32,
    pub looping: bool,
}

#[derive(Debug, Clone)]
pub struct VisualStateMachine {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub default_state: RowId,
    pub states: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct VisualState {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub state_key: String,
    pub animation: RowId,
}

#[derive(Debug, Clone)]
pub struct UnitVisual {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub state_machine: RowId,
    pub scale: f32,
    pub shadow_radius: f32,
    pub body_color: String,
}
