// Generated by belt data studio. Do not edit manually.

use data_studio_core::RowId;

#[derive(Debug, Clone)]
pub struct UnitDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub max_hp: i32,
    pub attack: i32,
    pub attack_range: f32,
    pub attack_interval: f32,
    pub move_speed: f32,
}

#[derive(Debug, Clone)]
pub struct UnitGroup {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub members: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct WaveDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub enemy_groups: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct MapDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub party: RowId,
    pub waves: Vec<RowId>,
    pub left_scroll_speed: f32,
    pub wave_spawn_x: f32,
}

