// Generated by belt data studio. Do not edit manually.

use data_studio_core::RowId;

#[derive(Debug, Clone)]
pub struct UnitDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub max_hp: i32,
    pub attack: i32,
    pub attack_range: f32,
    pub attack_interval: f32,
    pub move_speed: f32,
    pub visual: RowId,
    pub skills: Vec<RowId>,
    pub behavior_rules: Vec<RowId>,
    pub base_stats: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct UnitGroup {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub members: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct WaveDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub enemy_groups: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct MapDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub party: RowId,
    pub waves: Vec<RowId>,
    pub left_scroll_speed: f32,
    pub wave_spawn_x: f32,
    pub energy_cost: i32,
    pub drop_table: RowId,
}

#[derive(Debug, Clone)]
pub struct UnitGroupMember {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub unit: RowId,
    pub x: f32,
    pub lane: f32,
}

#[derive(Debug, Clone)]
pub struct TextureAsset {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub path: String,
    pub width: i32,
    pub height: i32,
}

#[derive(Debug, Clone)]
pub struct SpriteAnimation {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub texture: RowId,
    pub frame_count: i32,
    pub fps: f32,
    pub looping: bool,
    pub frames: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct VisualStateMachine {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub default_state: RowId,
    pub states: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct VisualState {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub state_key: String,
    pub animation: RowId,
}

#[derive(Debug, Clone)]
pub struct UnitVisual {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub state_machine: RowId,
    pub scale: f32,
    pub shadow_radius: f32,
    pub body_color: String,
}

#[derive(Debug, Clone)]
pub struct SpriteFrame {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub texture: RowId,
    pub x: i32,
    pub y: i32,
    pub w: i32,
    pub h: i32,
    pub pivot_x: f32,
    pub pivot_y: f32,
    pub duration: f32,
}

#[derive(Debug, Clone)]
pub struct ItemDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub category: String,
    pub rarity: String,
    pub stack_size: i32,
    pub description: String,
}

#[derive(Debug, Clone)]
pub struct DropTable {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub entries: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct DropEntry {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub item: RowId,
    pub min_quantity: i32,
    pub max_quantity: i32,
    pub chance_per_10000: i32,
}

#[derive(Debug, Clone)]
pub struct AccountEnergyConfig {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub max_energy: i32,
    pub recover_seconds: i32,
    pub recover_amount: i32,
}

#[derive(Debug, Clone)]
pub struct StorageTabConfig {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub tab_key: String,
    pub item_category: String,
    pub base_capacity: i32,
    pub upgrade_currency: RowId,
    pub upgrade_cost_base: i32,
}

#[derive(Debug, Clone)]
pub struct SkillDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub cooldown_ticks: i32,
    pub range: f32,
    pub cast_pattern: RowId,
    pub steps: Vec<RowId>,
    pub costs: Vec<RowId>,
    pub target_rule: String,
}

#[derive(Debug, Clone)]
pub struct SkillStep {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub tick_offset: i32,
    pub origin: String,
    pub pattern: RowId,
    pub effects: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct SkillEffect {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub effect_kind: String,
    pub power: i32,
    pub scaling: f32,
    pub knockback_cells: i32,
    pub trigger_skill: RowId,
    pub trigger_timing: String,
    pub impact_pattern: RowId,
    pub stat_target: String,
    pub stat: RowId,
    pub stat_delta: f32,
    pub stat_duration_ticks: i32,
    pub stat_tick_delta: f32,
}

#[derive(Debug, Clone)]
pub struct CellPattern {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub facing_mode: String,
    pub cells: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct CellOffset {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub forward: i32,
    pub side: i32,
}

#[derive(Debug, Clone)]
pub struct BehaviorRule {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub priority: i32,
    pub skill: RowId,
    pub condition: String,
    pub conditions: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct StatDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub value_kind: String,
    pub default_value: f32,
    pub min_value: f32,
    pub max_value: f32,
    pub category: String,
}

#[derive(Debug, Clone)]
pub struct UnitBaseStat {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub stat: RowId,
    pub value: f32,
}

#[derive(Debug, Clone)]
pub struct ConditionDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub condition_kind: String,
    pub subject: String,
    pub stat: RowId,
    pub operator: String,
    pub compare_mode: String,
    pub value: f32,
    pub other_stat: RowId,
}

#[derive(Debug, Clone)]
pub struct SkillStatCost {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub stat: RowId,
    pub amount: f32,
}

#[derive(Debug, Clone)]
pub struct AlchemyRecipe {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub output_item: RowId,
    pub output_quantity: i32,
    pub ingredients: Vec<RowId>,
    pub device: String,
}

#[derive(Debug, Clone)]
pub struct RecipeIngredient {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub item: RowId,
    pub quantity: i32,
}

#[derive(Debug, Clone)]
pub struct ForgeRecipe {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub recipe_item: RowId,
    pub output_item: RowId,
    pub output_quantity: i32,
    pub ingredients: Vec<RowId>,
    pub device: String,
}

#[derive(Debug, Clone)]
pub struct ForgeIngredient {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub item: RowId,
    pub quantity: i32,
    pub slot_kind: String,
}

#[derive(Debug, Clone)]
pub struct RefinementRecipe {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub input_equipment: RowId,
    pub material_item: RowId,
    pub material_quantity: i32,
    pub output_item: RowId,
    pub effect_kind: String,
    pub device: String,
    pub special_options: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct SpecialOptionDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub rarity: String,
    pub description: String,
    pub stat_deltas: Vec<RowId>,
    pub granted_skill: RowId,
    pub trigger_key: String,
    pub effect_summary: String,
}

#[derive(Debug, Clone)]
pub struct SpecialOptionStatDelta {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub stat: RowId,
    pub value: f32,
    pub condition: String,
}

#[derive(Debug, Clone)]
pub struct UnitSpecialOptionLoadout {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub unit: RowId,
    pub special_options: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct SpecialTriggerDef {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub interval_seconds: f32,
    pub stack_stat: RowId,
    pub stack_delta: f32,
    pub stack_threshold: f32,
    pub consume_stacks_on_trigger: bool,
    pub duration_seconds: f32,
    pub periodic_interval_seconds: f32,
    pub damage_scale: f32,
    pub target_rule: String,
    pub conditions: Vec<RowId>,
    pub effects: Vec<RowId>,
}

#[derive(Debug, Clone)]
pub struct SpecialTriggerCondition {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub condition_kind: String,
    pub stat: RowId,
    pub threshold: f32,
    pub consume_on_pass: bool,
    pub target_rule: String,
    pub range: f32,
}

#[derive(Debug, Clone)]
pub struct SpecialTriggerEffect {
    pub id: RowId,
    pub key: String,
    pub name: String,
    pub timing: String,
    pub effect_kind: String,
    pub stat: RowId,
    pub stat_delta: f32,
    pub duration_seconds: f32,
    pub interval_seconds: f32,
    pub damage_scale: f32,
    pub target_rule: String,
    pub trigger_skill: RowId,
}
