// Generated by belt data studio. Do not edit manually.

#![allow(dead_code)]

use std::collections::HashMap;

use data_studio_core::{CellValue, DataProject, FieldId, RowData, RowId, TableId};

use crate::schema_types::*;

#[derive(Debug, Clone)]
pub struct GeneratedDatabase {
    pub unit_def: GeneratedTable<UnitDef>,
    pub unit_group: GeneratedTable<UnitGroup>,
    pub wave_def: GeneratedTable<WaveDef>,
    pub map_def: GeneratedTable<MapDef>,
    pub unit_group_member: GeneratedTable<UnitGroupMember>,
    pub texture_asset: GeneratedTable<TextureAsset>,
    pub sprite_animation: GeneratedTable<SpriteAnimation>,
    pub visual_state_machine: GeneratedTable<VisualStateMachine>,
    pub visual_state: GeneratedTable<VisualState>,
    pub unit_visual: GeneratedTable<UnitVisual>,
    pub sprite_frame: GeneratedTable<SpriteFrame>,
    pub item_def: GeneratedTable<ItemDef>,
    pub drop_table: GeneratedTable<DropTable>,
    pub drop_entry: GeneratedTable<DropEntry>,
    pub account_energy_config: GeneratedTable<AccountEnergyConfig>,
    pub storage_tab_config: GeneratedTable<StorageTabConfig>,
    pub skill_def: GeneratedTable<SkillDef>,
    pub skill_step: GeneratedTable<SkillStep>,
    pub skill_effect: GeneratedTable<SkillEffect>,
    pub cell_pattern: GeneratedTable<CellPattern>,
    pub cell_offset: GeneratedTable<CellOffset>,
    pub behavior_rule: GeneratedTable<BehaviorRule>,
    pub stat_def: GeneratedTable<StatDef>,
    pub unit_base_stat: GeneratedTable<UnitBaseStat>,
    pub condition_def: GeneratedTable<ConditionDef>,
    pub skill_stat_cost: GeneratedTable<SkillStatCost>,
    pub alchemy_recipe: GeneratedTable<AlchemyRecipe>,
    pub recipe_ingredient: GeneratedTable<RecipeIngredient>,
    pub forge_recipe: GeneratedTable<ForgeRecipe>,
    pub forge_ingredient: GeneratedTable<ForgeIngredient>,
    pub refinement_recipe: GeneratedTable<RefinementRecipe>,
    pub special_option_def: GeneratedTable<SpecialOptionDef>,
    pub special_option_stat_delta: GeneratedTable<SpecialOptionStatDelta>,
    pub unit_special_option_loadout: GeneratedTable<UnitSpecialOptionLoadout>,
    pub special_trigger_def: GeneratedTable<SpecialTriggerDef>,
    pub special_trigger_condition: GeneratedTable<SpecialTriggerCondition>,
    pub special_trigger_effect: GeneratedTable<SpecialTriggerEffect>,
    pub special_option_skill_mutation: GeneratedTable<SpecialOptionSkillMutation>,
}

#[derive(Debug, Clone)]
pub struct GeneratedTable<T> {
    pub rows: Vec<T>,
    by_id: HashMap<RowId, usize>,
    by_key: HashMap<String, usize>,
}

impl<T> GeneratedTable<T> {
    fn new(rows: Vec<T>, ids: Vec<RowId>, keys: Vec<String>) -> Self {
        let by_id = ids
            .into_iter()
            .enumerate()
            .map(|(index, id)| (id, index))
            .collect();
        let by_key = keys
            .into_iter()
            .enumerate()
            .map(|(index, key)| (key, index))
            .collect();
        Self {
            rows,
            by_id,
            by_key,
        }
    }

    pub fn get_by_id(&self, id: RowId) -> Option<&T> {
        self.by_id.get(&id).and_then(|index| self.rows.get(*index))
    }

    pub fn get_by_key(&self, key: &str) -> Option<&T> {
        self.by_key.get(key).and_then(|index| self.rows.get(*index))
    }
}

impl GeneratedDatabase {
    pub fn from_project(project: &DataProject) -> Result<Self, String> {
        Ok(Self {
            unit_def: load_unit_def(project)?,
            unit_group: load_unit_group(project)?,
            wave_def: load_wave_def(project)?,
            map_def: load_map_def(project)?,
            unit_group_member: load_unit_group_member(project)?,
            texture_asset: load_texture_asset(project)?,
            sprite_animation: load_sprite_animation(project)?,
            visual_state_machine: load_visual_state_machine(project)?,
            visual_state: load_visual_state(project)?,
            unit_visual: load_unit_visual(project)?,
            sprite_frame: load_sprite_frame(project)?,
            item_def: load_item_def(project)?,
            drop_table: load_drop_table(project)?,
            drop_entry: load_drop_entry(project)?,
            account_energy_config: load_account_energy_config(project)?,
            storage_tab_config: load_storage_tab_config(project)?,
            skill_def: load_skill_def(project)?,
            skill_step: load_skill_step(project)?,
            skill_effect: load_skill_effect(project)?,
            cell_pattern: load_cell_pattern(project)?,
            cell_offset: load_cell_offset(project)?,
            behavior_rule: load_behavior_rule(project)?,
            stat_def: load_stat_def(project)?,
            unit_base_stat: load_unit_base_stat(project)?,
            condition_def: load_condition_def(project)?,
            skill_stat_cost: load_skill_stat_cost(project)?,
            alchemy_recipe: load_alchemy_recipe(project)?,
            recipe_ingredient: load_recipe_ingredient(project)?,
            forge_recipe: load_forge_recipe(project)?,
            forge_ingredient: load_forge_ingredient(project)?,
            refinement_recipe: load_refinement_recipe(project)?,
            special_option_def: load_special_option_def(project)?,
            special_option_stat_delta: load_special_option_stat_delta(project)?,
            unit_special_option_loadout: load_unit_special_option_loadout(project)?,
            special_trigger_def: load_special_trigger_def(project)?,
            special_trigger_condition: load_special_trigger_condition(project)?,
            special_trigger_effect: load_special_trigger_effect(project)?,
            special_option_skill_mutation: load_special_option_skill_mutation(project)?,
        })
    }
}

fn load_unit_def(project: &DataProject) -> Result<GeneratedTable<UnitDef>, String> {
    let rows = table_rows(project, TableId(1))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(UnitDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(1), "unit_def.name")?,
            max_hp: read_i32(row, FieldId(2), "unit_def.max_hp")?,
            attack: read_i32(row, FieldId(3), "unit_def.attack")?,
            attack_range: read_f32(row, FieldId(4), "unit_def.attack_range")?,
            attack_interval: read_f32(row, FieldId(5), "unit_def.attack_interval")?,
            move_speed: read_f32(row, FieldId(6), "unit_def.move_speed")?,
            visual: read_row(row, FieldId(7), "unit_def.visual")?,
            skills: read_rows(row, FieldId(8), "unit_def.skills")?,
            behavior_rules: read_rows(row, FieldId(9), "unit_def.behavior_rules")?,
            base_stats: read_rows(row, FieldId(10), "unit_def.base_stats")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_unit_group(project: &DataProject) -> Result<GeneratedTable<UnitGroup>, String> {
    let rows = table_rows(project, TableId(2))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(UnitGroup {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(10), "unit_group.name")?,
            members: read_rows(row, FieldId(11), "unit_group.members")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_wave_def(project: &DataProject) -> Result<GeneratedTable<WaveDef>, String> {
    let rows = table_rows(project, TableId(3))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(WaveDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(20), "wave_def.name")?,
            enemy_groups: read_rows(row, FieldId(21), "wave_def.enemy_groups")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_map_def(project: &DataProject) -> Result<GeneratedTable<MapDef>, String> {
    let rows = table_rows(project, TableId(4))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(MapDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(30), "map_def.name")?,
            party: read_row(row, FieldId(31), "map_def.party")?,
            waves: read_rows(row, FieldId(32), "map_def.waves")?,
            left_scroll_speed: read_f32(row, FieldId(33), "map_def.left_scroll_speed")?,
            wave_spawn_x: read_f32(row, FieldId(34), "map_def.wave_spawn_x")?,
            energy_cost: read_i32(row, FieldId(35), "map_def.energy_cost")?,
            drop_table: read_row(row, FieldId(36), "map_def.drop_table")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_unit_group_member(
    project: &DataProject,
) -> Result<GeneratedTable<UnitGroupMember>, String> {
    let rows = table_rows(project, TableId(5))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(UnitGroupMember {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(40), "unit_group_member.name")?,
            unit: read_row(row, FieldId(41), "unit_group_member.unit")?,
            x: read_f32(row, FieldId(42), "unit_group_member.x")?,
            lane: read_f32(row, FieldId(43), "unit_group_member.lane")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_texture_asset(project: &DataProject) -> Result<GeneratedTable<TextureAsset>, String> {
    let rows = table_rows(project, TableId(6))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(TextureAsset {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(44), "texture_asset.name")?,
            path: read_string(row, FieldId(45), "texture_asset.path")?,
            width: read_i32(row, FieldId(46), "texture_asset.width")?,
            height: read_i32(row, FieldId(47), "texture_asset.height")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_sprite_animation(project: &DataProject) -> Result<GeneratedTable<SpriteAnimation>, String> {
    let rows = table_rows(project, TableId(7))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpriteAnimation {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(50), "sprite_animation.name")?,
            texture: read_row(row, FieldId(51), "sprite_animation.texture")?,
            frame_count: read_i32(row, FieldId(52), "sprite_animation.frame_count")?,
            fps: read_f32(row, FieldId(53), "sprite_animation.fps")?,
            looping: read_bool(row, FieldId(54), "sprite_animation.looping")?,
            frames: read_rows(row, FieldId(55), "sprite_animation.frames")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_visual_state_machine(
    project: &DataProject,
) -> Result<GeneratedTable<VisualStateMachine>, String> {
    let rows = table_rows(project, TableId(8))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(VisualStateMachine {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(60), "visual_state_machine.name")?,
            default_state: read_row(row, FieldId(61), "visual_state_machine.default_state")?,
            states: read_rows(row, FieldId(62), "visual_state_machine.states")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_visual_state(project: &DataProject) -> Result<GeneratedTable<VisualState>, String> {
    let rows = table_rows(project, TableId(9))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(VisualState {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(70), "visual_state.name")?,
            state_key: read_string(row, FieldId(71), "visual_state.state_key")?,
            animation: read_row(row, FieldId(72), "visual_state.animation")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_unit_visual(project: &DataProject) -> Result<GeneratedTable<UnitVisual>, String> {
    let rows = table_rows(project, TableId(10))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(UnitVisual {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(80), "unit_visual.name")?,
            state_machine: read_row(row, FieldId(81), "unit_visual.state_machine")?,
            scale: read_f32(row, FieldId(82), "unit_visual.scale")?,
            shadow_radius: read_f32(row, FieldId(83), "unit_visual.shadow_radius")?,
            body_color: read_string(row, FieldId(84), "unit_visual.body_color")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_sprite_frame(project: &DataProject) -> Result<GeneratedTable<SpriteFrame>, String> {
    let rows = table_rows(project, TableId(11))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpriteFrame {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(90), "sprite_frame.name")?,
            texture: read_row(row, FieldId(91), "sprite_frame.texture")?,
            x: read_i32(row, FieldId(92), "sprite_frame.x")?,
            y: read_i32(row, FieldId(93), "sprite_frame.y")?,
            w: read_i32(row, FieldId(94), "sprite_frame.w")?,
            h: read_i32(row, FieldId(95), "sprite_frame.h")?,
            pivot_x: read_f32(row, FieldId(96), "sprite_frame.pivot_x")?,
            pivot_y: read_f32(row, FieldId(97), "sprite_frame.pivot_y")?,
            duration: read_f32(row, FieldId(98), "sprite_frame.duration")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_item_def(project: &DataProject) -> Result<GeneratedTable<ItemDef>, String> {
    let rows = table_rows(project, TableId(12))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(ItemDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(100), "item_def.name")?,
            category: read_string(row, FieldId(101), "item_def.category")?,
            rarity: read_string(row, FieldId(102), "item_def.rarity")?,
            stack_size: read_i32(row, FieldId(103), "item_def.stack_size")?,
            description: read_string(row, FieldId(104), "item_def.description")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_drop_table(project: &DataProject) -> Result<GeneratedTable<DropTable>, String> {
    let rows = table_rows(project, TableId(13))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(DropTable {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(110), "drop_table.name")?,
            entries: read_rows(row, FieldId(111), "drop_table.entries")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_drop_entry(project: &DataProject) -> Result<GeneratedTable<DropEntry>, String> {
    let rows = table_rows(project, TableId(14))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(DropEntry {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(120), "drop_entry.name")?,
            item: read_row(row, FieldId(121), "drop_entry.item")?,
            min_quantity: read_i32(row, FieldId(122), "drop_entry.min_quantity")?,
            max_quantity: read_i32(row, FieldId(123), "drop_entry.max_quantity")?,
            chance_per_10000: read_i32(row, FieldId(124), "drop_entry.chance_per_10000")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_account_energy_config(
    project: &DataProject,
) -> Result<GeneratedTable<AccountEnergyConfig>, String> {
    let rows = table_rows(project, TableId(15))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(AccountEnergyConfig {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(130), "account_energy_config.name")?,
            max_energy: read_i32(row, FieldId(131), "account_energy_config.max_energy")?,
            recover_seconds: read_i32(row, FieldId(132), "account_energy_config.recover_seconds")?,
            recover_amount: read_i32(row, FieldId(133), "account_energy_config.recover_amount")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_storage_tab_config(
    project: &DataProject,
) -> Result<GeneratedTable<StorageTabConfig>, String> {
    let rows = table_rows(project, TableId(16))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(StorageTabConfig {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(140), "storage_tab_config.name")?,
            tab_key: read_string(row, FieldId(141), "storage_tab_config.tab_key")?,
            item_category: read_string(row, FieldId(142), "storage_tab_config.item_category")?,
            base_capacity: read_i32(row, FieldId(143), "storage_tab_config.base_capacity")?,
            upgrade_currency: read_row(row, FieldId(144), "storage_tab_config.upgrade_currency")?,
            upgrade_cost_base: read_i32(row, FieldId(145), "storage_tab_config.upgrade_cost_base")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_skill_def(project: &DataProject) -> Result<GeneratedTable<SkillDef>, String> {
    let rows = table_rows(project, TableId(17))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SkillDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(150), "skill_def.name")?,
            cooldown_ticks: read_i32(row, FieldId(151), "skill_def.cooldown_ticks")?,
            range: read_f32(row, FieldId(156), "skill_def.range")?,
            cast_pattern: read_row(row, FieldId(152), "skill_def.cast_pattern")?,
            steps: read_rows(row, FieldId(153), "skill_def.steps")?,
            costs: read_rows(row, FieldId(155), "skill_def.costs")?,
            target_rule: read_string(row, FieldId(154), "skill_def.target_rule")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_skill_step(project: &DataProject) -> Result<GeneratedTable<SkillStep>, String> {
    let rows = table_rows(project, TableId(18))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SkillStep {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(160), "skill_step.name")?,
            tick_offset: read_i32(row, FieldId(161), "skill_step.tick_offset")?,
            origin: read_string(row, FieldId(162), "skill_step.origin")?,
            pattern: read_row(row, FieldId(163), "skill_step.pattern")?,
            effects: read_rows(row, FieldId(164), "skill_step.effects")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_skill_effect(project: &DataProject) -> Result<GeneratedTable<SkillEffect>, String> {
    let rows = table_rows(project, TableId(19))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SkillEffect {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(170), "skill_effect.name")?,
            effect_kind: read_string(row, FieldId(171), "skill_effect.effect_kind")?,
            power: read_i32(row, FieldId(172), "skill_effect.power")?,
            scaling: read_f32(row, FieldId(173), "skill_effect.scaling")?,
            knockback_cells: read_i32(row, FieldId(174), "skill_effect.knockback_cells")?,
            trigger_skill: read_row(row, FieldId(175), "skill_effect.trigger_skill")?,
            trigger_timing: read_string(row, FieldId(176), "skill_effect.trigger_timing")?,
            impact_pattern: read_row(row, FieldId(177), "skill_effect.impact_pattern")?,
            stat_target: read_string(row, FieldId(310), "skill_effect.stat_target")?,
            stat: read_row(row, FieldId(311), "skill_effect.stat")?,
            stat_delta: read_f32(row, FieldId(312), "skill_effect.stat_delta")?,
            stat_duration_ticks: read_i32(row, FieldId(313), "skill_effect.stat_duration_ticks")?,
            stat_tick_delta: read_f32(row, FieldId(314), "skill_effect.stat_tick_delta")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_cell_pattern(project: &DataProject) -> Result<GeneratedTable<CellPattern>, String> {
    let rows = table_rows(project, TableId(20))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(CellPattern {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(180), "cell_pattern.name")?,
            facing_mode: read_string(row, FieldId(181), "cell_pattern.facing_mode")?,
            cells: read_rows(row, FieldId(182), "cell_pattern.cells")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_cell_offset(project: &DataProject) -> Result<GeneratedTable<CellOffset>, String> {
    let rows = table_rows(project, TableId(21))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(CellOffset {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(190), "cell_offset.name")?,
            forward: read_i32(row, FieldId(191), "cell_offset.forward")?,
            side: read_i32(row, FieldId(192), "cell_offset.side")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_behavior_rule(project: &DataProject) -> Result<GeneratedTable<BehaviorRule>, String> {
    let rows = table_rows(project, TableId(22))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(BehaviorRule {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(200), "behavior_rule.name")?,
            priority: read_i32(row, FieldId(201), "behavior_rule.priority")?,
            skill: read_row(row, FieldId(202), "behavior_rule.skill")?,
            condition: read_string(row, FieldId(203), "behavior_rule.condition")?,
            conditions: read_rows(row, FieldId(204), "behavior_rule.conditions")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_stat_def(project: &DataProject) -> Result<GeneratedTable<StatDef>, String> {
    let rows = table_rows(project, TableId(23))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(StatDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(210), "stat_def.name")?,
            value_kind: read_string(row, FieldId(211), "stat_def.value_kind")?,
            default_value: read_f32(row, FieldId(212), "stat_def.default_value")?,
            min_value: read_f32(row, FieldId(213), "stat_def.min_value")?,
            max_value: read_f32(row, FieldId(214), "stat_def.max_value")?,
            category: read_string(row, FieldId(215), "stat_def.category")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_unit_base_stat(project: &DataProject) -> Result<GeneratedTable<UnitBaseStat>, String> {
    let rows = table_rows(project, TableId(24))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(UnitBaseStat {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(220), "unit_base_stat.name")?,
            stat: read_row(row, FieldId(221), "unit_base_stat.stat")?,
            value: read_f32(row, FieldId(222), "unit_base_stat.value")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_condition_def(project: &DataProject) -> Result<GeneratedTable<ConditionDef>, String> {
    let rows = table_rows(project, TableId(25))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(ConditionDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(230), "condition_def.name")?,
            condition_kind: read_string(row, FieldId(231), "condition_def.condition_kind")?,
            subject: read_string(row, FieldId(232), "condition_def.subject")?,
            stat: read_row(row, FieldId(233), "condition_def.stat")?,
            operator: read_string(row, FieldId(234), "condition_def.operator")?,
            compare_mode: read_string(row, FieldId(235), "condition_def.compare_mode")?,
            value: read_f32(row, FieldId(236), "condition_def.value")?,
            other_stat: read_row(row, FieldId(237), "condition_def.other_stat")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_skill_stat_cost(project: &DataProject) -> Result<GeneratedTable<SkillStatCost>, String> {
    let rows = table_rows(project, TableId(26))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SkillStatCost {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(240), "skill_stat_cost.name")?,
            stat: read_row(row, FieldId(241), "skill_stat_cost.stat")?,
            amount: read_f32(row, FieldId(242), "skill_stat_cost.amount")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_alchemy_recipe(project: &DataProject) -> Result<GeneratedTable<AlchemyRecipe>, String> {
    let rows = table_rows(project, TableId(27))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(AlchemyRecipe {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(250), "alchemy_recipe.name")?,
            output_item: read_row(row, FieldId(251), "alchemy_recipe.output_item")?,
            output_quantity: read_i32(row, FieldId(252), "alchemy_recipe.output_quantity")?,
            ingredients: read_rows(row, FieldId(253), "alchemy_recipe.ingredients")?,
            device: read_string(row, FieldId(254), "alchemy_recipe.device")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_recipe_ingredient(
    project: &DataProject,
) -> Result<GeneratedTable<RecipeIngredient>, String> {
    let rows = table_rows(project, TableId(28))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(RecipeIngredient {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(260), "recipe_ingredient.name")?,
            item: read_row(row, FieldId(261), "recipe_ingredient.item")?,
            quantity: read_i32(row, FieldId(262), "recipe_ingredient.quantity")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_forge_recipe(project: &DataProject) -> Result<GeneratedTable<ForgeRecipe>, String> {
    let rows = table_rows(project, TableId(29))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(ForgeRecipe {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(270), "forge_recipe.name")?,
            recipe_item: read_row(row, FieldId(271), "forge_recipe.recipe_item")?,
            output_item: read_row(row, FieldId(272), "forge_recipe.output_item")?,
            output_quantity: read_i32(row, FieldId(273), "forge_recipe.output_quantity")?,
            ingredients: read_rows(row, FieldId(274), "forge_recipe.ingredients")?,
            device: read_string(row, FieldId(275), "forge_recipe.device")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_forge_ingredient(project: &DataProject) -> Result<GeneratedTable<ForgeIngredient>, String> {
    let rows = table_rows(project, TableId(30))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(ForgeIngredient {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(280), "forge_ingredient.name")?,
            item: read_row(row, FieldId(281), "forge_ingredient.item")?,
            quantity: read_i32(row, FieldId(282), "forge_ingredient.quantity")?,
            slot_kind: read_string(row, FieldId(283), "forge_ingredient.slot_kind")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_refinement_recipe(
    project: &DataProject,
) -> Result<GeneratedTable<RefinementRecipe>, String> {
    let rows = table_rows(project, TableId(31))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(RefinementRecipe {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(290), "refinement_recipe.name")?,
            input_equipment: read_row(row, FieldId(291), "refinement_recipe.input_equipment")?,
            material_item: read_row(row, FieldId(292), "refinement_recipe.material_item")?,
            material_quantity: read_i32(row, FieldId(293), "refinement_recipe.material_quantity")?,
            output_item: read_row(row, FieldId(294), "refinement_recipe.output_item")?,
            effect_kind: read_string(row, FieldId(295), "refinement_recipe.effect_kind")?,
            device: read_string(row, FieldId(296), "refinement_recipe.device")?,
            special_options: read_rows(row, FieldId(297), "refinement_recipe.special_options")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_special_option_def(
    project: &DataProject,
) -> Result<GeneratedTable<SpecialOptionDef>, String> {
    let rows = table_rows(project, TableId(32))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpecialOptionDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(300), "special_option_def.name")?,
            rarity: read_string(row, FieldId(301), "special_option_def.rarity")?,
            description: read_string(row, FieldId(302), "special_option_def.description")?,
            stat_deltas: read_rows(row, FieldId(303), "special_option_def.stat_deltas")?,
            granted_skill: read_row(row, FieldId(304), "special_option_def.granted_skill")?,
            trigger_key: read_string(row, FieldId(305), "special_option_def.trigger_key")?,
            effect_summary: read_string(row, FieldId(306), "special_option_def.effect_summary")?,
            skill_mutations: read_rows(row, FieldId(307), "special_option_def.skill_mutations")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_special_option_stat_delta(
    project: &DataProject,
) -> Result<GeneratedTable<SpecialOptionStatDelta>, String> {
    let rows = table_rows(project, TableId(33))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpecialOptionStatDelta {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(310), "special_option_stat_delta.name")?,
            stat: read_row(row, FieldId(311), "special_option_stat_delta.stat")?,
            value: read_f32(row, FieldId(312), "special_option_stat_delta.value")?,
            condition: read_string(row, FieldId(313), "special_option_stat_delta.condition")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_unit_special_option_loadout(
    project: &DataProject,
) -> Result<GeneratedTable<UnitSpecialOptionLoadout>, String> {
    let rows = table_rows(project, TableId(34))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(UnitSpecialOptionLoadout {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(320), "unit_special_option_loadout.name")?,
            unit: read_row(row, FieldId(321), "unit_special_option_loadout.unit")?,
            special_options: read_rows(
                row,
                FieldId(322),
                "unit_special_option_loadout.special_options",
            )?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_special_trigger_def(
    project: &DataProject,
) -> Result<GeneratedTable<SpecialTriggerDef>, String> {
    let rows = table_rows(project, TableId(35))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpecialTriggerDef {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(330), "special_trigger_def.name")?,
            interval_seconds: read_f32(row, FieldId(331), "special_trigger_def.interval_seconds")?,
            stack_stat: read_row(row, FieldId(332), "special_trigger_def.stack_stat")?,
            stack_delta: read_f32(row, FieldId(333), "special_trigger_def.stack_delta")?,
            stack_threshold: read_f32(row, FieldId(334), "special_trigger_def.stack_threshold")?,
            consume_stacks_on_trigger: read_bool(
                row,
                FieldId(335),
                "special_trigger_def.consume_stacks_on_trigger",
            )?,
            duration_seconds: read_f32(row, FieldId(336), "special_trigger_def.duration_seconds")?,
            periodic_interval_seconds: read_f32(
                row,
                FieldId(337),
                "special_trigger_def.periodic_interval_seconds",
            )?,
            damage_scale: read_f32(row, FieldId(338), "special_trigger_def.damage_scale")?,
            target_rule: read_string(row, FieldId(339), "special_trigger_def.target_rule")?,
            conditions: read_rows(row, FieldId(340), "special_trigger_def.conditions")?,
            effects: read_rows(row, FieldId(341), "special_trigger_def.effects")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_special_trigger_condition(
    project: &DataProject,
) -> Result<GeneratedTable<SpecialTriggerCondition>, String> {
    let rows = table_rows(project, TableId(36))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpecialTriggerCondition {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(350), "special_trigger_condition.name")?,
            condition_kind: read_string(
                row,
                FieldId(351),
                "special_trigger_condition.condition_kind",
            )?,
            stat: read_row(row, FieldId(352), "special_trigger_condition.stat")?,
            threshold: read_f32(row, FieldId(353), "special_trigger_condition.threshold")?,
            consume_on_pass: read_bool(
                row,
                FieldId(354),
                "special_trigger_condition.consume_on_pass",
            )?,
            target_rule: read_string(row, FieldId(355), "special_trigger_condition.target_rule")?,
            range: read_f32(row, FieldId(356), "special_trigger_condition.range")?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_special_trigger_effect(
    project: &DataProject,
) -> Result<GeneratedTable<SpecialTriggerEffect>, String> {
    let rows = table_rows(project, TableId(37))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpecialTriggerEffect {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(360), "special_trigger_effect.name")?,
            timing: read_string(row, FieldId(361), "special_trigger_effect.timing")?,
            effect_kind: read_string(row, FieldId(362), "special_trigger_effect.effect_kind")?,
            stat: read_row(row, FieldId(363), "special_trigger_effect.stat")?,
            stat_delta: read_f32(row, FieldId(364), "special_trigger_effect.stat_delta")?,
            duration_seconds: read_f32(
                row,
                FieldId(365),
                "special_trigger_effect.duration_seconds",
            )?,
            interval_seconds: read_f32(
                row,
                FieldId(366),
                "special_trigger_effect.interval_seconds",
            )?,
            damage_scale: read_f32(row, FieldId(367), "special_trigger_effect.damage_scale")?,
            target_rule: read_string(row, FieldId(368), "special_trigger_effect.target_rule")?,
            trigger_skill: read_row(row, FieldId(369), "special_trigger_effect.trigger_skill")?,
            pay_skill_cost: read_bool(row, FieldId(370), "special_trigger_effect.pay_skill_cost")?,
            require_skill_cooldown: read_bool(
                row,
                FieldId(371),
                "special_trigger_effect.require_skill_cooldown",
            )?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn load_special_option_skill_mutation(
    project: &DataProject,
) -> Result<GeneratedTable<SpecialOptionSkillMutation>, String> {
    let rows = table_rows(project, TableId(38))?;
    let mut typed_rows = Vec::new();
    let mut ids = Vec::new();
    let mut keys = Vec::new();
    for row in rows {
        typed_rows.push(SpecialOptionSkillMutation {
            id: row.id,
            key: row.key.clone(),
            name: read_string(row, FieldId(380), "special_option_skill_mutation.name")?,
            target_skill: read_row(
                row,
                FieldId(381),
                "special_option_skill_mutation.target_skill",
            )?,
            mutation_kind: read_string(
                row,
                FieldId(382),
                "special_option_skill_mutation.mutation_kind",
            )?,
            damage_scale_delta: read_f32(
                row,
                FieldId(383),
                "special_option_skill_mutation.damage_scale_delta",
            )?,
            cooldown_ticks_delta: read_i32(
                row,
                FieldId(384),
                "special_option_skill_mutation.cooldown_ticks_delta",
            )?,
            range_delta: read_f32(
                row,
                FieldId(385),
                "special_option_skill_mutation.range_delta",
            )?,
        });
        ids.push(row.id);
        keys.push(row.key.clone());
    }
    Ok(GeneratedTable::new(typed_rows, ids, keys))
}

fn table_rows(project: &DataProject, table_id: TableId) -> Result<&[RowData], String> {
    project
        .data
        .iter()
        .find(|table| table.table_id == table_id)
        .map(|table| table.rows.as_slice())
        .ok_or_else(|| format!("missing table data {:?}", table_id))
}

fn cell<'a>(row: &'a RowData, field_id: FieldId, label: &str) -> Result<&'a CellValue, String> {
    row.cells
        .get(&field_id)
        .ok_or_else(|| format!("missing cell {label} in row {}", row.key))
}

fn read_bool(row: &RowData, field_id: FieldId, label: &str) -> Result<bool, String> {
    match cell(row, field_id, label)? {
        CellValue::Bool(value) => Ok(*value),
        value => Err(format!("expected bool for {label}, got {value:?}")),
    }
}

fn read_i32(row: &RowData, field_id: FieldId, label: &str) -> Result<i32, String> {
    match cell(row, field_id, label)? {
        CellValue::I32(value) => Ok(*value),
        value => Err(format!("expected i32 for {label}, got {value:?}")),
    }
}

fn read_i64(row: &RowData, field_id: FieldId, label: &str) -> Result<i64, String> {
    match cell(row, field_id, label)? {
        CellValue::I64(value) => Ok(*value),
        value => Err(format!("expected i64 for {label}, got {value:?}")),
    }
}

fn read_f32(row: &RowData, field_id: FieldId, label: &str) -> Result<f32, String> {
    match cell(row, field_id, label)? {
        CellValue::F32(value) => Ok(*value),
        value => Err(format!("expected f32 for {label}, got {value:?}")),
    }
}

fn read_string(row: &RowData, field_id: FieldId, label: &str) -> Result<String, String> {
    match cell(row, field_id, label)? {
        CellValue::String(value) => Ok(value.clone()),
        value => Err(format!("expected string for {label}, got {value:?}")),
    }
}

fn read_row(row: &RowData, field_id: FieldId, label: &str) -> Result<RowId, String> {
    match cell(row, field_id, label)? {
        CellValue::Row(value) => Ok(*value),
        value => Err(format!("expected row id for {label}, got {value:?}")),
    }
}

fn read_rows(row: &RowData, field_id: FieldId, label: &str) -> Result<Vec<RowId>, String> {
    match cell(row, field_id, label)? {
        CellValue::Rows(value) => Ok(value.clone()),
        value => Err(format!("expected row id list for {label}, got {value:?}")),
    }
}
